services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\MailerModule\ZikulaMailerModule'

    Zikula\MailerModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'
